"""egitmen_performans tablosu eklendi

Revision ID: 3029ac3fbb65
Revises: 7a27a2e8bd2d
Create Date: 2025-12-26 12:16:29.021133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3029ac3fbb65'
down_revision = '7a27a2e8bd2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('egitmen_performanslar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('egitmen_id', sa.Integer(), nullable=False),
    sa.Column('yil', sa.Integer(), nullable=False),
    sa.Column('ay', sa.Integer(), nullable=False),
    sa.Column('kriter', sa.String(length=500), nullable=False),
    sa.Column('hafta1', sa.Integer(), nullable=True),
    sa.Column('hafta2', sa.Integer(), nullable=True),
    sa.Column('hafta3', sa.Integer(), nullable=True),
    sa.Column('hafta4', sa.Integer(), nullable=True),
    sa.Column('olusturma_tarihi', sa.DateTime(), nullable=True),
    sa.Column('guncelleme_tarihi', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['egitmen_id'], ['egitmenler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('egitmen_performanslar')
    # ### end Alembic commands ###
