"""Sinif modeli guncellendi

Revision ID: 409bcf90ca81
Revises: 4683b5581dd0
Create Date: 2025-12-24 12:30:14.280572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409bcf90ca81'
down_revision = '4683b5581dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('siniflar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kod', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('egitmen_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('seviye', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tur', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('kontenjan', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ders_gunleri', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('ders_saati', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('aciklama', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_siniflar_egitmen', 'egitmenler', ['egitmen_id'], ['id'])
        batch_op.drop_column('kapasite')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('siniflar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kapasite', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('aciklama')
        batch_op.drop_column('ders_saati')
        batch_op.drop_column('ders_gunleri')
        batch_op.drop_column('kontenjan')
        batch_op.drop_column('tur')
        batch_op.drop_column('seviye')
        batch_op.drop_column('egitmen_id')
        batch_op.drop_column('kod')

    # ### end Alembic commands ###
