"""Initial migration

Revision ID: 4683b5581dd0
Revises: 
Create Date: 2025-11-21 01:35:52.997503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4683b5581dd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kullanicilar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adsoyad', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('tur', sa.Integer(), nullable=False),
    sa.Column('kaynak_id', sa.Integer(), nullable=True),
    sa.Column('yetkiler', sa.Text(), nullable=True),
    sa.Column('sms_user', sa.String(length=50), nullable=True),
    sa.Column('sms_pass', sa.String(length=50), nullable=True),
    sa.Column('sms_apikey', sa.String(length=100), nullable=True),
    sa.Column('sms_saglayici', sa.Integer(), nullable=True),
    sa.Column('sms_title', sa.String(length=11), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kullanicilar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kullanicilar_email'), ['email'], unique=True)

    op.create_table('muftulukler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adi', sa.String(length=200), nullable=False),
    sa.Column('sehir', sa.String(length=100), nullable=True),
    sa.Column('bag', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kurslar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adi', sa.String(length=200), nullable=False),
    sa.Column('kod', sa.String(length=50), nullable=True),
    sa.Column('adres', sa.Text(), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('muftu_id', sa.Integer(), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('ayarlar', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['muftu_id'], ['muftulukler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('egitmenler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adsoyad', sa.String(length=100), nullable=False),
    sa.Column('tc', sa.String(length=11), nullable=True),
    sa.Column('dogum_tarihi', sa.Date(), nullable=True),
    sa.Column('cinsiyet', sa.String(length=1), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('adres', sa.Text(), nullable=True),
    sa.Column('kurs_id', sa.Integer(), nullable=False),
    sa.Column('brans', sa.String(length=100), nullable=True),
    sa.Column('egitim_durumu', sa.String(length=100), nullable=True),
    sa.Column('mezuniyet', sa.String(length=200), nullable=True),
    sa.Column('baslangic_tarihi', sa.Date(), nullable=True),
    sa.Column('gorev', sa.String(length=100), nullable=True),
    sa.Column('ucret', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('foto', sa.Integer(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kurs_id'], ['kurslar.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tc')
    )
    with op.batch_alter_table('egitmenler', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_egitmenler_adsoyad'), ['adsoyad'], unique=False)
        batch_op.create_index(batch_op.f('ix_egitmenler_kurs_id'), ['kurs_id'], unique=False)

    op.create_table('siniflar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adi', sa.String(length=100), nullable=False),
    sa.Column('kurs_id', sa.Integer(), nullable=False),
    sa.Column('kapasite', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['kurs_id'], ['kurslar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dersler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adi', sa.String(length=100), nullable=False),
    sa.Column('kurs_id', sa.Integer(), nullable=False),
    sa.Column('sinif_id', sa.Integer(), nullable=True),
    sa.Column('egitmen_id', sa.Integer(), nullable=True),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('baslangic_saati', sa.Time(), nullable=True),
    sa.Column('bitis_saati', sa.Time(), nullable=True),
    sa.Column('tur', sa.String(length=50), nullable=True),
    sa.Column('konu', sa.Text(), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['egitmen_id'], ['egitmenler.id'], ),
    sa.ForeignKeyConstraint(['kurs_id'], ['kurslar.id'], ),
    sa.ForeignKeyConstraint(['sinif_id'], ['siniflar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dersler', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dersler_tarih'), ['tarih'], unique=False)

    op.create_table('ogrenciler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adsoyad', sa.String(length=100), nullable=False),
    sa.Column('tc', sa.String(length=11), nullable=True),
    sa.Column('dogum_tarihi', sa.Date(), nullable=True),
    sa.Column('dogum_yeri', sa.String(length=100), nullable=True),
    sa.Column('cinsiyet', sa.String(length=1), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('adres', sa.Text(), nullable=True),
    sa.Column('veli_adi', sa.String(length=100), nullable=True),
    sa.Column('veli_telefon', sa.String(length=20), nullable=True),
    sa.Column('veli_email', sa.String(length=120), nullable=True),
    sa.Column('kurs_id', sa.Integer(), nullable=False),
    sa.Column('sinif_id', sa.Integer(), nullable=True),
    sa.Column('egitmen_id', sa.Integer(), nullable=True),
    sa.Column('sicil_no', sa.String(length=50), nullable=True),
    sa.Column('kayit_tarihi', sa.Date(), nullable=True),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('egitim_turu', sa.String(length=50), nullable=True),
    sa.Column('donem', sa.String(length=50), nullable=True),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['egitmen_id'], ['egitmenler.id'], ),
    sa.ForeignKeyConstraint(['kurs_id'], ['kurslar.id'], ),
    sa.ForeignKeyConstraint(['sinif_id'], ['siniflar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ogrenciler', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ogrenciler_adsoyad'), ['adsoyad'], unique=False)
        batch_op.create_index(batch_op.f('ix_ogrenciler_kurs_id'), ['kurs_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ogrenciler_sicil_no'), ['sicil_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_ogrenciler_tc'), ['tc'], unique=True)

    op.create_table('aidat_hareketleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ogrenci_id', sa.Integer(), nullable=False),
    sa.Column('kurs_id', sa.Integer(), nullable=False),
    sa.Column('tutar', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('donem', sa.String(length=50), nullable=True),
    sa.Column('aciklama', sa.Text(), nullable=True),
    sa.Column('odendi', sa.Boolean(), nullable=True),
    sa.Column('odeme_tarihi', sa.Date(), nullable=True),
    sa.Column('odeme_sekli', sa.String(length=50), nullable=True),
    sa.Column('vade_tarihi', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['kullanicilar.id'], ),
    sa.ForeignKeyConstraint(['kurs_id'], ['kurslar.id'], ),
    sa.ForeignKeyConstraint(['ogrenci_id'], ['ogrenciler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aidat_hareketleri', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aidat_hareketleri_ogrenci_id'), ['ogrenci_id'], unique=False)

    op.create_table('hafizlik_dersler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ogrenci_id', sa.Integer(), nullable=False),
    sa.Column('egitmen_id', sa.Integer(), nullable=False),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('sure', sa.String(length=50), nullable=True),
    sa.Column('ayet_baslangic', sa.Integer(), nullable=True),
    sa.Column('ayet_bitis', sa.Integer(), nullable=True),
    sa.Column('sayfa_baslangic', sa.Integer(), nullable=True),
    sa.Column('sayfa_bitis', sa.Integer(), nullable=True),
    sa.Column('basari_durumu', sa.String(length=20), nullable=True),
    sa.Column('puan', sa.Integer(), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['egitmen_id'], ['egitmenler.id'], ),
    sa.ForeignKeyConstraint(['ogrenci_id'], ['ogrenciler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hafizlik_dersler', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hafizlik_dersler_ogrenci_id'), ['ogrenci_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hafizlik_dersler_tarih'), ['tarih'], unique=False)

    op.create_table('sinav_sonuclari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ogrenci_id', sa.Integer(), nullable=False),
    sa.Column('sinav_id', sa.Integer(), nullable=False),
    sa.Column('puan', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ogrenci_id'], ['ogrenciler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sinav_sonuclari', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sinav_sonuclari_ogrenci_id'), ['ogrenci_id'], unique=False)

    op.create_table('yoklamalar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ogrenci_id', sa.Integer(), nullable=False),
    sa.Column('ders_id', sa.Integer(), nullable=True),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('durum', sa.String(length=20), nullable=True),
    sa.Column('mazeret', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['kullanicilar.id'], ),
    sa.ForeignKeyConstraint(['ders_id'], ['dersler.id'], ),
    sa.ForeignKeyConstraint(['ogrenci_id'], ['ogrenciler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('yoklamalar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_yoklamalar_ogrenci_id'), ['ogrenci_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_yoklamalar_tarih'), ['tarih'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yoklamalar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_yoklamalar_tarih'))
        batch_op.drop_index(batch_op.f('ix_yoklamalar_ogrenci_id'))

    op.drop_table('yoklamalar')
    with op.batch_alter_table('sinav_sonuclari', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sinav_sonuclari_ogrenci_id'))

    op.drop_table('sinav_sonuclari')
    with op.batch_alter_table('hafizlik_dersler', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hafizlik_dersler_tarih'))
        batch_op.drop_index(batch_op.f('ix_hafizlik_dersler_ogrenci_id'))

    op.drop_table('hafizlik_dersler')
    with op.batch_alter_table('aidat_hareketleri', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aidat_hareketleri_ogrenci_id'))

    op.drop_table('aidat_hareketleri')
    with op.batch_alter_table('ogrenciler', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ogrenciler_tc'))
        batch_op.drop_index(batch_op.f('ix_ogrenciler_sicil_no'))
        batch_op.drop_index(batch_op.f('ix_ogrenciler_kurs_id'))
        batch_op.drop_index(batch_op.f('ix_ogrenciler_adsoyad'))

    op.drop_table('ogrenciler')
    with op.batch_alter_table('dersler', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dersler_tarih'))

    op.drop_table('dersler')
    op.drop_table('siniflar')
    with op.batch_alter_table('egitmenler', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_egitmenler_kurs_id'))
        batch_op.drop_index(batch_op.f('ix_egitmenler_adsoyad'))

    op.drop_table('egitmenler')
    op.drop_table('kurslar')
    op.drop_table('muftulukler')
    with op.batch_alter_table('kullanicilar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kullanicilar_email'))

    op.drop_table('kullanicilar')
    # ### end Alembic commands ###
