"""ogrenci_performans_tablosu_eklendi

Revision ID: 7a27a2e8bd2d
Revises: ee931bd1c4d5
Create Date: 2025-12-26 11:33:59.235952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a27a2e8bd2d'
down_revision = 'ee931bd1c4d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ogrenci_performanslar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ogrenci_id', sa.Integer(), nullable=False),
    sa.Column('kurs_id', sa.Integer(), nullable=False),
    sa.Column('sinif_id', sa.Integer(), nullable=True),
    sa.Column('tarih', sa.Date(), nullable=False),
    sa.Column('veri_turu', sa.String(length=20), nullable=True),
    sa.Column('ders_calisma_disiplini', sa.Integer(), nullable=True),
    sa.Column('ders_verme_performansi', sa.Integer(), nullable=True),
    sa.Column('sistem_uygulanma_disiplini', sa.Integer(), nullable=True),
    sa.Column('ders_okuyus_hizi', sa.Integer(), nullable=True),
    sa.Column('talim_tecvid_durumu', sa.Integer(), nullable=True),
    sa.Column('ders_verme_zamanlamasi', sa.Integer(), nullable=True),
    sa.Column('sayfa_dinleme_disiplini', sa.Integer(), nullable=True),
    sa.Column('kuran_kulturune_uyum', sa.Integer(), nullable=True),
    sa.Column('hafta_basinda_kurs_zamanlamasi_giris', sa.Integer(), nullable=True),
    sa.Column('ders_saatlerinde_sinifa_zamanlama_giris_mutabaa_saatleri', sa.Integer(), nullable=True),
    sa.Column('kultur_saatlari_ders_zamanlama_giris', sa.Integer(), nullable=True),
    sa.Column('sinif_hoca_ile_iletisim', sa.Integer(), nullable=True),
    sa.Column('arkadaslariyla_iletisim', sa.Integer(), nullable=True),
    sa.Column('namaz_vakitlerinde_mescide_zamanlama_giris', sa.Integer(), nullable=True),
    sa.Column('ibadet_disiplini', sa.Integer(), nullable=True),
    sa.Column('kilkiyafet_disiplini', sa.Integer(), nullable=True),
    sa.Column('yeme_icme_disiplini', sa.Integer(), nullable=True),
    sa.Column('yatalakhane_disiplini', sa.Integer(), nullable=True),
    sa.Column('trafic_kontrolu_kendini_cikisine_becerisi_temizlik_ve_duzen', sa.Integer(), nullable=True),
    sa.Column('genel_disiplin', sa.Integer(), nullable=True),
    sa.Column('notlar', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kurs_id'], ['kurslar.id'], ),
    sa.ForeignKeyConstraint(['ogrenci_id'], ['ogrenciler.id'], ),
    sa.ForeignKeyConstraint(['sinif_id'], ['siniflar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ogrenci_performanslar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ogrenci_performanslar_ogrenci_id'), ['ogrenci_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ogrenci_performanslar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ogrenci_performanslar_ogrenci_id'))

    op.drop_table('ogrenci_performanslar')
    # ### end Alembic commands ###
