"""karne sablonlari eklendi

Revision ID: ee931bd1c4d5
Revises: 409bcf90ca81
Create Date: 2025-12-25 12:31:32.900530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee931bd1c4d5'
down_revision = '409bcf90ca81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('karne_sablonlar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adi', sa.String(length=200), nullable=False),
    sa.Column('arkaplan', sa.String(length=500), nullable=True),
    sa.Column('genislik', sa.Integer(), nullable=True),
    sa.Column('yukseklik', sa.Integer(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=True),
    sa.Column('kurs_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kurs_id'], ['kurslar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('karne_sablon_elemanlari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sablon_id', sa.Integer(), nullable=False),
    sa.Column('tip', sa.String(length=50), nullable=False),
    sa.Column('anahtar', sa.String(length=200), nullable=True),
    sa.Column('metin', sa.String(length=500), nullable=True),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('font_boyut', sa.Integer(), nullable=True),
    sa.Column('font_renk', sa.String(length=20), nullable=True),
    sa.Column('font_stili', sa.String(length=50), nullable=True),
    sa.Column('hizalama', sa.String(length=20), nullable=True),
    sa.Column('genislik', sa.Integer(), nullable=True),
    sa.Column('sira', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sablon_id'], ['karne_sablonlar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('karne_sablon_elemanlari')
    op.drop_table('karne_sablonlar')
    # ### end Alembic commands ###
